### ISSUE TITLE
Enable browser dropdown list for previously entered terms

### ISSUE THREAD

**Issue by hans-juergen** [RudeySH/lastfm-bulk-edit#10]
The bulk edit script seems to disable the usual browser-based dropdown list if you enter a name that you already have edited before. This works for the usual bulk editing of tracks without the script, but not with it. This dropdown list of previously entered terms can be handy when doing similar edits like changing the album artist to "Various Artists" for example, as you only have to type the first character to make it appear then.

**Comment by RudeySH** [comment]
The script disables the browser's history-based autocomplete feature because it provides it's own datalist of items to use for autocomplete. Let me explain what I mean.

![image](https://user-images.githubusercontent.com/3918757/113396997-ace80480-939c-11eb-953b-bdbd3ee241c0.png)

When bulk-editing an artist, the track and album fields are often "Mixed". In the image above, the scrobbles that are being edited are scrobbled on 12 different albums. The script disables the browser's autocomplete and instead provides a dropdown list based on those 12 albums, see the image below.

![image](https://user-images.githubusercontent.com/3918757/113397019-b2454f00-939c-11eb-8879-8d55bf87e3ee.png)

While it's possible to combine this list with the browser's history-based dropdown list, I'd rather not do that. Doing so may be confusing, users wouldn't be able to tell what items from such combined list are part of the history, or part of the 12 albums (in the example above). However...

![image](https://user-images.githubusercontent.com/3918757/113398014-38ae6080-939e-11eb-8e09-554e020c9e9a.png)

As the image above might suggest, the script also replaces the browser's history-based autocomplete for fields that only have one known value.

At the very least, the script can be changed to keep the browser's history on for fields that are not "Mixed". Would this change be sufficient for your use case, @hans-juergen?

**Comment by hans-juergen** [comment]
Right, probably that would be enough if the dropdown worked for only one autocomplete item. I often have the case that I have to manually type "Various Artists" as the album artist and wished I could only type a single "v" to click on it with the mouse.

**Comment by RudeySH** [comment]
Alright, v0.3.4 is out now and it restores the browser's autocomplete for fields that are not in the "Mixed" state.

As for your other suggestions, unfortunately these dropdown menus can't be customized because those are provided by the browser themselves, not the website or script. I can't add popups or trashcan icons to these dropdowns.

**Comment by hans-juergen** [comment]
And thanks again, great!

**Comment by hans-juergen** [comment]
It seems that using the browser's autocomplete feature does not work anymore. As your script has not been updated, I guess there was a change somewhere else? I am currently using MS Edge, but will check in Opera as well.
