### ISSUE TITLE
406 Not Acceptable errors

### ISSUE THREAD

**Issue by melat0nin** [RudeySH/lastfm-bulk-edit#19]
Great script! It worked for me once, and now I'm getting lots of `406 Not Acceptable` server responses, and the javascript error 'There was a problem loading your scrobbles, please try again later.'

This happens even if I try to edit a single scrobble -- the popup displays with the loading spinner, then ~40% in it stops with the javascript error.

![image](https://user-images.githubusercontent.com/912688/178751723-81f10f24-9bae-45bf-b482-1ba2c05f898b.png)

**Comment by RudeySH** [comment]
Does this happen when bulk editing any artist, album or track? If it is happening on specific artists/albums/tracks, please link them here along with your Last.fm profile link.

What browsers did you try? And which userscript manager, Violentmonkey or Tampermonkey?

**Comment by melat0nin** [comment]
Strangely, it just worked again after leaving things alone for an hour. But now it's not working (again, same error). Is is possible there's some kind of API rate limit?

I'm running Firefox 103 beta on Windows 11, with `lastfm-bulk-edit` 0.5.2 through Violentmonkey. The problem arises on every artists/album I've tried (I attempted a selection, with different characters in their titles etc.)

**Comment by RudeySH** [comment]
I'm getting this issue right now as well. I'm not sure if it's rate limiting. If it is, they're using the wrong HTTP status code. This issue does not just affect my script, but the Last.fm website itself as well. It's very strange.

When viewing the list of tracks of an artist in a user's library, everything loads fine until you click "Next" or "2" to view the second page of tracks.

- This works (200 OK):
  https://www.last.fm/user/RudeySH/library/music/Silverstein/+tracks
- This doesn't work (406 Not Acceptable):
  https://www.last.fm/user/RudeySH/library/music/Silverstein/+tracks?page=2
  ![image](https://user-images.githubusercontent.com/3918757/178928702-79a6f8ec-4b80-4ca2-9e7f-ed735f5c5aa5.png)

The same thing also happens when viewing the list of scrobbles on a track page. For example:
- This works (200 OK):
  https://www.last.fm/user/RudeySH/library/music/Silverstein/_/Smashed+Into+Pieces
- This doesn't work (406 Not Acceptable):
  https://www.last.fm/user/RudeySH/library/music/Silverstein/_/Smashed+Into+Pieces?page=2

There seems to be something wrong with the `page` query parameter. Even `page=1` results in a 406.

I created a topic about this issue on the Last.fm Support Forums: https://support.last.fm/t/error-406-not-acceptable-when-viewing-the-second-page-of-tracks-scrobbles-under-any-artist-in-my-library/62549

**Comment by RudeySH** [comment]
A couple of hours after I created that topic on the Last.fm Support Forums, the moderator @hans-juergen replied the following message:

> Staff has investigated this issue again and believes to have fixed it.

I haven't seen a 406 since my last comment, but I also don't use my script very often.
