### ISSUE TITLE
Showing all Automatic Edits at once causes page to misbehave

### ISSUE THREAD

**Issue by thereddestdog** [RudeySH/lastfm-bulk-edit#25]
Here's some screenshots of my Automatic Edits page after clicking the Show All button:

Normal view:
![image](https://github.com/RudeySH/lastfm-bulk-edit/assets/24947579/614754f2-5d31-4800-92f9-d2a1a515c19b)

Soon after clicking the page expands horizontally:
![image](https://github.com/RudeySH/lastfm-bulk-edit/assets/24947579/55b06f5b-ced8-4888-9c0c-d277ae232862)

Scrolling over shows rendering issues:
![image](https://github.com/RudeySH/lastfm-bulk-edit/assets/24947579/c323e13e-2a5d-4d4b-ae84-dd76ff96d786)

**Comment by RudeySH** [comment]
This happened because the Last.fm Bulk Edit userscript changes the table layout so that the columns are sized to match their contents. If all columns contain long names, the table becomes too wide. This almost never happens on any page of 10 automatic edits, but this happens commonly when viewing all automatic edits at once.

To fix this, I have made it so that the userscript only changes the table layout when not viewing all automatic edits at once. Version 1.1.5 contains this fix.

**Comment by RudeySH** [comment]
I just realized that the fix was not included in 1.1.5. However, it should be included 1.2.0, which is available now.
