### ISSUE TITLE
There was a problem loading your scrobbles, please try again later.

### ISSUE THREAD

**Issue by safxaasf** [RudeySH/lastfm-bulk-edit#39]
When I click on “edit artist scrobbles” I get this error (There was a problem loading your scrobbles, please try again later.) and then redirected to this page:

> 
> You’re requesting too many pages
> 
> You're requesting a lot of pages which may slow down the site for other users. Why not take a break and enjoy a cup of tea?

![qxwer](https://github.com/RudeySH/lastfm-bulk-edit/assets/172035019/76c87352-239e-45f5-b8a1-13512f84e848)

**Comment by zachrank** [comment]
Ditto, seems Luke they're rate-limiting the site more aggressively as of late.

**Comment by samantha-owens** [comment]
I've been having the same issue all day whenever I try to bulk edit.

**Comment by catzs** [comment]
I'm getting the same issue, can't edit scrobbles at all with the script enabled.

**Comment by Smithsix** [comment]
Alas, here too.

Hope this isn't the end.

**Comment by DIZZYDJC** [comment]
same issue, do we think this can be resolved?

**Comment by thomas-harding** [comment]
Still happening at the moment. Hoping LFM isn't cracking down on big requests

**Comment by RudeySH** [comment]
I just updated the bulk edit script so that it can handle Last.fm's rate limiting. Please reinstall the script to update it to version 1.5. Let me know if you still have issues after this.

I did some testing. Since Friday, Last.fm only allows users to load up to 20 pages per minute. Before this, the script was loading as many pages as it needed, all simultaneously. This allowed the script to be relatively fast when loading hundreds of scrobbles. Now, I've made it so that the script will only ever load 6 pages simultaneously. In addition, when the script gets rate limited, it will now halt all requests and it attempts to resume every 10 seconds (it usually takes up to 60 seconds before it can successfully resume).

With these changes, the bulk edit script takes about 7 minutes to load 1000 scrobbles. This sucks, it used to be only a handful of seconds before Last.fm's update... But in the current situation, I don't see a way to make it faster than this.

**Comment by safxaasf** [comment]
the problem still seems to persist, when I try to edit an album with 18 scrobbles - I still get redirected

>You’re requesting too many pages

**Comment by RudeySH** [comment]
@safxaasf Does the issue occur when loading scrobbles, or when saving edits?

I have only seen the rate limiting affect the loading of scrobbles, not the saving of edits. Nevertheless, today I have updated the script again (version 1.5.1) so that it can handle rate limiting while saving edits (if that ever occurs).

To update the script, simply do step 3 of these [instructions](https://github.com/RudeySH/lastfm-bulk-edit?tab=readme-ov-file#instructions).

Let me know if you still have issues with v1.5.1.

**Comment by tkohhh** [comment]
I installed the script for the first time today, and I am getting this error.  I've disable the script for now.  Is there any more information on this?

**Comment by RudeySH** [comment]
When do you get this error?

You will get this error while the script is loading scrobbles and you're browsing your Last.fm library in another tab. But the script should be able to successfully load the scrobbles regardless.

**Comment by tkohhh** [comment]
I only ever have one tab open for Last.fm.  I think what happened is I 'X'ed out of a "Loading Scrobbles" because it was taking too long and then resumed browsing.

**Comment by tkohhh** [comment]
Got it... thank you for the response!
