### ISSUE TITLE
Don't follow track redirects

### ISSUE THREAD

**Issue by rzumer** [RudeySH/lastfm-bulk-edit#4]
Trying to bulk edit an album to change the artist name, one track was skipped and not detected as being scrobbled, because it redirects to the corrected artist name on the site (小椋 佳 - また旅仕度 -> 小椋佳 - また旅仕度). I had to go and edit it manually by inserting a +noredirect in the URL leading to my scrobbles of this track. If possible this script should ignore such redirects.

**Comment by RudeySH** [comment]
This should now be fixed in v0.3.3 (10e2983ca44c868b6afa218d611557b3e897f3bc).

The script already ignored redirects when artist and track corrections were turned off. But due to an error in the code it was misunderstanding which URLs point to an artist's page, and which URLs point to an album page, when corrections were turned off. This ultimately led to the script not always being able to find all of your scrobbled tracks.

Let me know if you still have issues with v0.3.3 or future versions.
