### ISSUE TITLE
Not working since v3.3 implemented?

### ISSUE THREAD

**Issue by d4goo** [RudeySH/lastfm-bulk-edit#9]
I thought this may have been a last.fm server issue (as most are), but after a few days - and noting that the non-script single item editing is working fine - it appears I've not been able to get the script to work since v3.3 was implemented.  All looks normal, but then nothing actually changes after the save process completes.  Is anyone else seeing this?  Individual editing has worked fine throughout the weekend, but any bulk edits fail to change the data.

**Comment by alexandersx** [comment]
same thing has been happening with me, the single item updates with no problem but when it's bulk editing the change doesn't happen

**Comment by RudeySH** [comment]
This is actually a Last.fm issue. While single scrobble edits still work, Last.fm's "bulk edit" checkbox is broken since a couple of days. As soon as you check this box, editing scrobbles no longer works.

The lastfm-bulk-edit userscript relies on Last.fm's "bulk edit" feature to implement its true bulk editing capabilities. This means that as long as Last.fm's bulk edit checkbox is not working, this script will not work as well.

There's already a thread about this on Last.fm's support forums: https://support.last.fm/t/bulk-edit-stopped-working/42260/19. Thankfully, the mods have acknowledged the issue and have notified the Last.fm staff.

I'll keep this GitHub issue open for visibility purposes, and will close this when Last.fm has fixed the issue on their end.

**Comment by d4goo** [comment]
Sorry has missed this last.fm forum post. Thanks for updating us, and
leaving this open until they resolve the issue.

**Comment by alexandersx** [comment]
it's officially been fixed just letting you guys know!

**Comment by d4goo** [comment]
Yes, tested and working again.  Thanks!
